=== EV081/HCKT-CLOUD/DataGenerator/schemas-validation/conexiones.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Conexiones",
  "type": "object",
  "x-dynamodb": {
    "partition_key": "conexion_id"
  },
  "properties": {
    "conexion_id": { "type": "string" },

    "usuario_correo": {
      "type": "string",
      "format": "email"
    },

    "rol": {
      "type": "string",
      "enum": ["estudiante", "personal_administrativo", "autoridad"]
    },

    "created_at": {
      "type": "string",
      "format": "date-time"
    },

    "expiracion_ttl": {
      "type": "number"
    }
  },

  "required": [
    "conexion_id",
    "usuario_correo",
    "created_at",
    "expiracion_ttl"
  ],

  "additionalProperties": false
}

=== EV081/HCKT-CLOUD/DataGenerator/example-data/conexiones.json
[
  {
    "conexion_id": "d7f1c867-53f5-4c17-8cc8-871abf571810",
    "usuario_correo": "isabel.ramírez@outlook.com",
    "rol": "estudiante",
    "created_at": "2025-11-17T00:52:50.299895",
    "expiracion_ttl": 1763355170
  },
  {
    "conexion_id": "9ae11005-036f-483c-aac3-af5f0556eae8",
    "usuario_correo": "andrés.silva@gmail.com",
    "rol": "personal_administrativo",
    "created_at": "2025-11-16T23:27:50.299932",
    "expiracion_ttl": 1763350070
  },
  {
    "conexion_id": "5e4cdf0b-fe0e-4f13-82fb-30eaa4eebb48",
    "usuario_correo": "pedro.flores@outlook.com",
    "rol": "estudiante",
    "created_at": "2025-11-17T01:11:50.299958",
    "expiracion_ttl": 1763356310
  },
  {
    "conexion_id": "f0fe00ae-d5f2-4e5c-a001-76c65075bbb7",
    "usuario_correo": "maría.garcía@utec.edu.pe",
    "rol": "estudiante",
    "created_at": "2025-11-16T23:52:50.299978",
    "expiracion_ttl": 1763351570
  },
  {
    "conexion_id": "80aa95c6-7676-4305-b5d6-d99d9f9976c2",
    "usuario_correo": "maría.garcía@gmail.com",
    "rol": "estudiante",
    "created_at": "2025-11-16T23:56:50.299996",
    "expiracion_ttl": 1763351810
  },
  {
    "conexion_id": "bb553b2d-4e18-439e-96fb-2aa0dd642138",
    "usuario_correo": "laura.sánchez@utec.edu.pe",
    "rol": "personal_administrativo",
    "created_at": "2025-11-17T00:40:50.300015",
    "expiracion_ttl": 1763354450
  },
  {
    "conexion_id": "d828f7ae-2b8e-4569-9d27-af5351ff9cb4",
    "usuario_correo": "laura.sánchez@utec.edu.pe",
    "rol": "personal_administrativo",
    "created_at": "2025-11-16T23:51:50.300034",
    "expiracion_ttl": 1763351510
  },
  {
    "conexion_id": "d93a37c9-26a5-49af-94d9-bbacc0651a20",
    "usuario_correo": "josé.gonzález@utec.edu.pe",
    "rol": "personal_administrativo",
    "created_at": "2025-11-16T23:19:50.300052",
    "expiracion_ttl": 1763349590
  },
  {
    "conexion_id": "3fd2fcfb-009a-448a-96c5-4b2e2c8a8058",
    "usuario_correo": "carmen.fernández@outlook.com",
    "rol": "personal_administrativo",
    "created_at": "2025-11-16T23:43:50.300061",
    "expiracion_ttl": 1763351030
  },
  {
    "conexion_id": "981a19c5-36a1-458d-a301-280cd841a33c",
    "usuario_correo": "carmen.fernández@gmail.com",
    "rol": "estudiante",
    "created_at": "2025-11-17T00:59:50.300069",
    "expiracion_ttl": 1763355590
  }
]
